import * as cheerio from 'cheerio';
const ORIGIN='https://mob4g.com',TIMEOUT=15000;
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const abs=v=>{try{return new URL(v,ORIGIN).toString()}catch{return ''}};
const num=v=>{const m=clean(v).replace(/,/g,'').match(/(\d+(?:\.\d+)?)/);return m?Number(m[1]):0};
const year=v=>{const m=clean(v).match(/\b(20\d{2})\b/);return m?Number(m[1]):0};
async function request(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'Mozilla/5.0 (compatible; Mob4gCatalog/2.0)'}});if(!r.ok)throw Error(`mob4g HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
function rowValue(groups,label){for(const g of groups)for(const r of g.rows||[])if(r[0]===label)return clean(r[1]);return ''}
export default async function handler(req,res){try{const raw=String(req.query.url||''),u=new URL(raw,ORIGIN);if(u.origin!==ORIGIN||!u.pathname.startsWith('/specs/'))return res.status(400).json({ok:false,error:'Only mob4g.com/specs URLs are allowed'});const $=cheerio.load(await request(u.toString())),groups=[];let current=null;$('h2,h3,table').each((_,el)=>{const tag=String(el.tagName||'').toLowerCase();if(tag==='h2'||tag==='h3'){const title=clean($(el).text());current=title&&!/صور|مميزات|عيوب|السعر|مراجعة|الخلاصة/i.test(title)?{title,rows:[]}:null;if(current)groups.push(current);return}if(!current)return;$(el).find('tr').each((__,tr)=>{const cells=$(tr).find('th,td').map((___,x)=>clean($(x).text())).get().filter(Boolean);if(cells.length>=2)current.rows.push([cells[0],cells.slice(1).join(' | ')])})});const title=clean($('h1').first().text())||clean($('meta[property="og:title"]').attr('content'))||clean($('title').first().text());const release=rowValue(groups,'تاريخ صدور الجهاز')||rowValue(groups,'تاريخ الإصدار');const announced=rowValue(groups,'تاريخ اعلان عن الجهاز')||rowValue(groups,'تاريخ الإعلان');const releaseYear=year(release)||year(announced);const priceText=clean($('.price,.price-box,.post-price').first().text())||clean(textForPrice($));const pm=priceText.match(/(\d[\d,]*(?:\.\d+)?)\s*\$/)||clean($.text()).match(/السعر[^$\d]{0,120}(\d[\d,]*(?:\.\d+)?)\s*\$/i);const price=pm?num(pm[1]):0;const brand=rowValue(groups,'الماركة');const category=rowValue(groups,'الفئة');const rating=num(clean($.text()).match(/التقييم[^\d]{0,50}(\d+(?:\.\d+)?)/i)?.[1]);let mainImg='';const candidates=['main img','.entry-content img','article img','figure img'];for(const sel of candidates){const src=abs($(sel).first().attr('src')||$(sel).first().attr('data-src')||$(sel).first().attr('data-lazy-src')||'');if(src&&!/logo|icon|avatar/i.test(src)){mainImg=src;break}}if(!mainImg){const h1=$('h1').first();const src=abs(h1.closest('article').find('img').first().attr('src')||'');if(src&&!/logo|icon|avatar/i.test(src))mainImg=src}if(!mainImg){const src=abs($('img').first().attr('src')||'');if(src&&!/logo|icon|avatar/i.test(src))mainImg=src}const images=mainImg?[mainImg]:[];if(releaseYear&&releaseYear<2022)return res.status(200).json({ok:true,eligible:false,releaseYear,title,url:u.toString()});res.setHeader('Cache-Control','public, s-maxage=604800, stale-while-revalidate=2592000');res.setHeader('Content-Type','application/json; charset=utf-8');res.status(200).json({ok:true,eligible:releaseYear>=2022,url:u.toString(),title,brand,category,price,rating,release,releaseYear,images,groups:groups.filter(g=>g.rows.length)})}catch(e){res.status(502).json({ok:false,error:String(e?.message||e)})}}
function textForPrice($){return clean($('.entry-content,.post-content,article,main').first().text())}
